pub const DEBIAN_LOGO: [&str; 15] = [
    "\x1b[31m        _,met$$$$$gg.      ",
    "\x1b[31m     ,g$$$$$$$$$$$$$$$P.   \x1b[0m",
    "\x1b[31m   ,g$$P\"\"       \"\"\"Y$$.\". ",
    "\x1b[31m  ,$$P'              `$$$. ",
    "\x1b[31m',$$P       ,ggs.     `$$b:",
    "\x1b[31m`d$$'     ,$P\"'   .    $$$ ",
    "\x1b[31m $$P      d$'     ,    $$P ",
    "\x1b[31m $$:      $$.   -    ,d$$' ",
    "\x1b[31m $$;      Y$b._   _,d$P'   ",
    "\x1b[31m Y$$.    `.`\"Y$$$$P\"'      ",
    "\x1b[31m `$$b      \"-.__           ",
    "\x1b[31m  `Y$$b                    ",
    "\x1b[31m   `Y$$.                   ",
    "\x1b[31m      `Y$$b.               ",
    "\x1b[31m           `\"\"\"\"           ",
];

pub const ARCH_LOGO: [&str; 15] = [
    "\x1b[36m                -`                ",
    "\x1b[36m               .o+`               ",
    "\x1b[36m              `ooo/`              ",
    "\x1b[36m             +oooooo:             ",
    "\x1b[36m            -+oooooo+:            ",
    "\x1b[36m           /:-:++oooo+:           ",
    "\x1b[36m          /++++++++++++:          ",
    "\x1b[36m        `/+++ooooooooooo/`        ",
    "\x1b[36m      .oosssso-````/osssss+`      ",
    "\x1b[36m     -ossssso.      :sssssso.     ",
    "\x1b[36m    :ossssss/        ossso+++.    ",
    "\x1b[36m  /osssso+/:-        -:/+ossso+-  ",
    "\x1b[36m `sso+:-`                `.-/+so: ",
    "\x1b[36m`++:.                        `-/+/",
    "\x1b[36m.`                              `/",
];

pub const FEDORA_LOGO: [&str; 15] = [
    "\x1b[34m            .',;;:::;;,'.          ",
    "\x1b[34m       .';cccccccccccccc:;,.       ",
    "\x1b[34m    .:cccccccccccccccccccccc:.     ",
    "\x1b[34m  .;cccccccccccc;\x1b[37m.:ddl:.\x1b[34m;ccccc;.   ",
    "\x1b[34m .:cccccccccccc;\x1b[37mOWMKOOXMWd\x1b[34m;ccccc:. ",
    "\x1b[34m.:cccccccccccc;\x1b[37mKMMc\x1b[34m;cc;\x1b[37mxMMc\x1b[34m;ccccc:.",
    "\x1b[34m,ccccccccccccc;\x1b[37mMMM.\x1b[34m;cc;;\x1b[37mWW:\x1b[34m;cccccc,",
    "\x1b[34m:ccccccccccccc;\x1b[37mMMM.\x1b[34m;cccccccccccccc:",
    "\x1b[34m:ccccccc;\x1b[37moxOOo\x1b[34m;\x1b[37mMMMOOOk.\x1b[34m;cccccccccc:",
    "\x1b[34mcccccc;\x1b[37mOMMKxdd\x1b[34m:\x1b[37mMMMkdc.\x1b[34m;ccccccccccc ",
    "\x1b[34mccccc;\x1b[37mXMO'\x1b[34m;ccc;\x1b[37mMMM.\x1b[34m;cccccccccccccc'",
    "\x1b[34mccccc;\x1b[37mOMNc.\x1b[34mccc\x1b[37m.xMMd\x1b[34m;cccccccccccc;  ",
    "\x1b[34mcccccc;\x1b[37mdNMWXXXWM0;\x1b[34m;ccccccccccc:,   ",
    "\x1b[34mccccccc;\x1b[37m.:odl:.\x1b[34m;ccccccccccc:,.     ",
    "\x1b[34m ':cccccccccccccccc::;,.           ",
];

pub const UBUNTU_LOGO: [&str; 15] = [
    "\x1b[31m                     ....                ",
    "\x1b[31m           .',:clooo:  .:looooo:.        ",
    "\x1b[31m      .;loooooool:,'   :oooooooooc       ",
    "\x1b[31m     ;loool;.          'oooooooooo,      ",
    "\x1b[31m   ;clool'              .oooooooc.  ,,   ",
    "\x1b[31m      ...                 ......  .:oo,  ",
    "\x1b[31m .;clol:,.                        .loooo'",
    "\x1b[31m:oooooooo,                         'ooool",
    "\x1b[31m,loooooooc.                       .loooo.",
    "\x1b[31m  .,;;;'.                          ;ooooc",
    "\x1b[31m      ...                          ,oool.",
    "\x1b[31m     ;ooooo:.             ;oooooc.  :l.  ",
    "\x1b[31m      .cooooooc,,..     cooooooooo.      ",
    "\x1b[31m          .':looooooo;  ,ooooooooc       ",
    "\x1b[31m              ..';::c'  .;loooooc:'      ",
];

pub const LINUX_LOGO: [&str; 15] = [
    "\x1b[20m           .-\"\"\"\"-.           ",
    "\x1b[20m          /,.  ,-.  \\         ",
    "\x1b[20m          |()L( ()| |         ",
    "\x1b[20m          |,'__`\".| |         ",
    "\x1b[20m         .j `--\"' `  `        ",
    "\x1b[20m        / '        '   \\      ",
    "\x1b[20m       / /         `   `.     ",
    "\x1b[20m     / /             l   |    ",
    "\x1b[20m    . ,              |   |    ",
    "\x1b[20m    ,\"`.            .|   |    ",
    "\x1b[33m _.'   ``.          | `..-'l  ",
    "\x1b[33m|       `.`,        |      `  ",
    "\x1b[33m|         `.    __.j         )",
    "\x1b[33m|__        |--\"\"___|      ,-' ",
    "\x1b[33m   `\"--...,+\"\"\"\"   `._,.-'    ",
];
